// Fichier GÉNÉRÉ par observateur/generer-noms.py — ne pas modifier à la main.
// Source : copie locale du jeu (version 1.12.0.11).

/** Une entrée d'énumération du jeu : sa clé technique et son nom français. */
export interface Nom {
  cle: string;
  fr: string;
}

export const BattleType: Readonly<Record<number, Nom>> = {
  0: { cle: "WILD", fr: "sauvage" },
  1: { cle: "TRAINER", fr: "dresseur" },
  2: { cle: "CLEAR", fr: "vide" },
  3: { cle: "MYSTERY_ENCOUNTER", fr: "rencontre mystère" },
};

export const BattlerIndex: Readonly<Record<number, Nom>> = {
  "-1": { cle: "ATTACKER", fr: "ATTACKER" },
  0: { cle: "PLAYER", fr: "PLAYER" },
  1: { cle: "PLAYER_2", fr: "PLAYER_2" },
  2: { cle: "ENEMY", fr: "ENEMY" },
  3: { cle: "ENEMY_2", fr: "ENEMY_2" },
};

export const BiomeId: Readonly<Record<number, Nom>> = {
  0: { cle: "TOWN", fr: "Ville" },
  1: { cle: "PLAINS", fr: "Plaines" },
  2: { cle: "GRASS", fr: "Herbes" },
  3: { cle: "TALL_GRASS", fr: "Hautes Herbes" },
  4: { cle: "METROPOLIS", fr: "Métropole" },
  5: { cle: "FOREST", fr: "Forêt" },
  6: { cle: "SEA", fr: "Mer" },
  7: { cle: "SWAMP", fr: "Marécage" },
  8: { cle: "BEACH", fr: "Plage" },
  9: { cle: "LAKE", fr: "Lac" },
  10: { cle: "SEABED", fr: "Fonds Marins" },
  11: { cle: "MOUNTAIN", fr: "Montagne" },
  12: { cle: "BADLANDS", fr: "Terres Sauvages" },
  13: { cle: "CAVE", fr: "Grotte" },
  14: { cle: "DESERT", fr: "Désert" },
  15: { cle: "ICE_CAVE", fr: "Caverne Gelée" },
  16: { cle: "MEADOW", fr: "Prairie" },
  17: { cle: "POWER_PLANT", fr: "Centrale" },
  18: { cle: "VOLCANO", fr: "Volcan" },
  19: { cle: "GRAVEYARD", fr: "Cimetière" },
  20: { cle: "DOJO", fr: "Dojo" },
  21: { cle: "FACTORY", fr: "Usine" },
  22: { cle: "RUINS", fr: "Ruines" },
  23: { cle: "WASTELAND", fr: "Terres Désolées" },
  24: { cle: "ABYSS", fr: "Gouffre" },
  25: { cle: "SPACE", fr: "Espace" },
  26: { cle: "CONSTRUCTION_SITE", fr: "Chantier" },
  27: { cle: "JUNGLE", fr: "Jungle" },
  28: { cle: "FAIRY_CAVE", fr: "Grotte Féérique" },
  29: { cle: "TEMPLE", fr: "Temple" },
  30: { cle: "SLUM", fr: "Bidonville" },
  31: { cle: "SNOWY_FOREST", fr: "Forêt Enneigée" },
  40: { cle: "ISLAND", fr: "Ile" },
  41: { cle: "LABORATORY", fr: "Laboratoire" },
  50: { cle: "END", fr: "???" },
};

export const Button: Readonly<Record<number, Nom>> = {
  0: { cle: "UP", fr: "UP" },
  1: { cle: "DOWN", fr: "DOWN" },
  2: { cle: "LEFT", fr: "LEFT" },
  3: { cle: "RIGHT", fr: "RIGHT" },
  4: { cle: "SUBMIT", fr: "SUBMIT" },
  5: { cle: "ACTION", fr: "ACTION" },
  6: { cle: "CANCEL", fr: "CANCEL" },
  7: { cle: "MENU", fr: "MENU" },
  8: { cle: "STATS", fr: "STATS" },
  9: { cle: "CYCLE_SHINY", fr: "CYCLE_SHINY" },
  10: { cle: "CYCLE_FORM", fr: "CYCLE_FORM" },
  11: { cle: "CYCLE_GENDER", fr: "CYCLE_GENDER" },
  12: { cle: "CYCLE_ABILITY", fr: "CYCLE_ABILITY" },
  13: { cle: "CYCLE_NATURE", fr: "CYCLE_NATURE" },
  14: { cle: "CYCLE_TERA", fr: "CYCLE_TERA" },
  15: { cle: "SPEED_UP", fr: "SPEED_UP" },
  16: { cle: "SLOW_DOWN", fr: "SLOW_DOWN" },
  17: { cle: "DEV_CUSTOM", fr: "DEV_CUSTOM" },
};

export const Command: Readonly<Record<number, Nom>> = {
  0: { cle: "FIGHT", fr: "FIGHT" },
  1: { cle: "BALL", fr: "BALL" },
  2: { cle: "POKEMON", fr: "POKEMON" },
  3: { cle: "RUN", fr: "RUN" },
  4: { cle: "TERA", fr: "TERA" },
};

export const MoveCategory: Readonly<Record<number, Nom>> = {
  0: { cle: "PHYSICAL", fr: "Physique" },
  1: { cle: "SPECIAL", fr: "Spéciale" },
  2: { cle: "STATUS", fr: "Statut" },
};

export const MoveTarget: Readonly<Record<number, Nom>> = {
  0: { cle: "USER", fr: "USER" },
  1: { cle: "OTHER", fr: "OTHER" },
  2: { cle: "ALL_OTHERS", fr: "ALL_OTHERS" },
  3: { cle: "NEAR_OTHER", fr: "NEAR_OTHER" },
  4: { cle: "ALL_NEAR_OTHERS", fr: "ALL_NEAR_OTHERS" },
  5: { cle: "NEAR_ENEMY", fr: "NEAR_ENEMY" },
  6: { cle: "ALL_NEAR_ENEMIES", fr: "ALL_NEAR_ENEMIES" },
  7: { cle: "RANDOM_NEAR_ENEMY", fr: "RANDOM_NEAR_ENEMY" },
  8: { cle: "ALL_ENEMIES", fr: "ALL_ENEMIES" },
  9: { cle: "ATTACKER", fr: "ATTACKER" },
  10: { cle: "NEAR_ALLY", fr: "NEAR_ALLY" },
  11: { cle: "ALLY", fr: "ALLY" },
  12: { cle: "USER_OR_NEAR_ALLY", fr: "USER_OR_NEAR_ALLY" },
  13: { cle: "USER_AND_ALLIES", fr: "USER_AND_ALLIES" },
  14: { cle: "ALL", fr: "ALL" },
  15: { cle: "USER_SIDE", fr: "USER_SIDE" },
  16: { cle: "ENEMY_SIDE", fr: "ENEMY_SIDE" },
  17: { cle: "BOTH_SIDES", fr: "BOTH_SIDES" },
  18: { cle: "PARTY", fr: "PARTY" },
  19: { cle: "CURSE", fr: "CURSE" },
};

export const MoveUseMode: Readonly<Record<number, Nom>> = {
  1: { cle: "NORMAL", fr: "NORMAL" },
  2: { cle: "IGNORE_PP", fr: "IGNORE_PP" },
  3: { cle: "INDIRECT", fr: "INDIRECT" },
  4: { cle: "FOLLOW_UP", fr: "FOLLOW_UP" },
  5: { cle: "REFLECTED", fr: "REFLECTED" },
  6: { cle: "DELAYED_ATTACK", fr: "DELAYED_ATTACK" },
};

export const Nature: Readonly<Record<number, Nom>> = {
  0: { cle: "HARDY", fr: "Hardi" },
  1: { cle: "LONELY", fr: "Solo" },
  2: { cle: "BRAVE", fr: "Brave" },
  3: { cle: "ADAMANT", fr: "Rigide" },
  4: { cle: "NAUGHTY", fr: "Mauvais" },
  5: { cle: "BOLD", fr: "Assuré" },
  6: { cle: "DOCILE", fr: "Docile" },
  7: { cle: "RELAXED", fr: "Relax" },
  8: { cle: "IMPISH", fr: "Malin" },
  9: { cle: "LAX", fr: "Lâche" },
  10: { cle: "TIMID", fr: "Timide" },
  11: { cle: "HASTY", fr: "Pressé" },
  12: { cle: "SERIOUS", fr: "Sérieux" },
  13: { cle: "JOLLY", fr: "Jovial" },
  14: { cle: "NAIVE", fr: "Naïf" },
  15: { cle: "MODEST", fr: "Modeste" },
  16: { cle: "MILD", fr: "Doux" },
  17: { cle: "QUIET", fr: "Discret" },
  18: { cle: "BASHFUL", fr: "Pudique" },
  19: { cle: "RASH", fr: "Foufou" },
  20: { cle: "CALM", fr: "Calme" },
  21: { cle: "GENTLE", fr: "Gentil" },
  22: { cle: "SASSY", fr: "Malpoli" },
  23: { cle: "CAREFUL", fr: "Prudent" },
  24: { cle: "QUIRKY", fr: "Bizarre" },
};

export const PokeballType: Readonly<Record<number, Nom>> = {
  0: { cle: "POKEBALL", fr: "Poké Ball" },
  1: { cle: "GREAT_BALL", fr: "Super Ball" },
  2: { cle: "ULTRA_BALL", fr: "Hyper Ball" },
  3: { cle: "ROGUE_BALL", fr: "Rogue Ball" },
  4: { cle: "MASTER_BALL", fr: "Master Ball" },
  5: { cle: "LUXURY_BALL", fr: "Luxe Ball" },
};

export const PokemonType: Readonly<Record<number, Nom>> = {
  "-1": { cle: "UNKNOWN", fr: "???" },
  0: { cle: "NORMAL", fr: "Normal" },
  1: { cle: "FIGHTING", fr: "Combat" },
  2: { cle: "FLYING", fr: "Vol" },
  3: { cle: "POISON", fr: "Poison" },
  4: { cle: "GROUND", fr: "Sol" },
  5: { cle: "ROCK", fr: "Roche" },
  6: { cle: "BUG", fr: "Insecte" },
  7: { cle: "GHOST", fr: "Spectre" },
  8: { cle: "STEEL", fr: "Acier" },
  9: { cle: "FIRE", fr: "Feu" },
  10: { cle: "WATER", fr: "Eau" },
  11: { cle: "GRASS", fr: "Plante" },
  12: { cle: "ELECTRIC", fr: "Électrik" },
  13: { cle: "PSYCHIC", fr: "Psy" },
  14: { cle: "ICE", fr: "Glace" },
  15: { cle: "DRAGON", fr: "Dragon" },
  16: { cle: "DARK", fr: "Ténèbres" },
  17: { cle: "FAIRY", fr: "Fée" },
  18: { cle: "STELLAR", fr: "Stellaire" },
};

export const StatusEffect: Readonly<Record<number, Nom>> = {
  0: { cle: "NONE", fr: "Aucun" },
  1: { cle: "POISON", fr: "Empoisonnement" },
  2: { cle: "TOXIC", fr: "Empoisonnement grave" },
  3: { cle: "PARALYSIS", fr: "Paralysie" },
  4: { cle: "SLEEP", fr: "Sommeil" },
  5: { cle: "FREEZE", fr: "Gelé" },
  6: { cle: "BURN", fr: "Brulure" },
  7: { cle: "FAINT", fr: "K.O." },
};

export const TerrainType: Readonly<Record<number, Nom>> = {
  0: { cle: "NONE", fr: "Aucun" },
  1: { cle: "MISTY", fr: "Brumeux" },
  2: { cle: "ELECTRIC", fr: "Électrifié" },
  3: { cle: "GRASSY", fr: "Herbu" },
  4: { cle: "PSYCHIC", fr: "Psychique" },
};

export const UiMode: Readonly<Record<number, Nom>> = {
  0: { cle: "MESSAGE", fr: "MESSAGE" },
  1: { cle: "TITLE", fr: "TITLE" },
  2: { cle: "COMMAND", fr: "COMMAND" },
  3: { cle: "FIGHT", fr: "FIGHT" },
  4: { cle: "BALL", fr: "BALL" },
  5: { cle: "TARGET_SELECT", fr: "TARGET_SELECT" },
  6: { cle: "MODIFIER_SELECT", fr: "MODIFIER_SELECT" },
  7: { cle: "SAVE_SLOT", fr: "SAVE_SLOT" },
  8: { cle: "PARTY", fr: "PARTY" },
  9: { cle: "SUMMARY", fr: "SUMMARY" },
  10: { cle: "STARTER_SELECT", fr: "STARTER_SELECT" },
  11: { cle: "EVOLUTION_SCENE", fr: "EVOLUTION_SCENE" },
  12: { cle: "EGG_HATCH_SCENE", fr: "EGG_HATCH_SCENE" },
  13: { cle: "EGG_HATCH_SUMMARY", fr: "EGG_HATCH_SUMMARY" },
  14: { cle: "CONFIRM", fr: "CONFIRM" },
  15: { cle: "OPTION_SELECT", fr: "OPTION_SELECT" },
  16: { cle: "MENU", fr: "MENU" },
  17: { cle: "MENU_OPTION_SELECT", fr: "MENU_OPTION_SELECT" },
  18: { cle: "SETTINGS", fr: "SETTINGS" },
  19: { cle: "SETTINGS_DISPLAY", fr: "SETTINGS_DISPLAY" },
  20: { cle: "SETTINGS_AUDIO", fr: "SETTINGS_AUDIO" },
  21: { cle: "SETTINGS_GAMEPAD", fr: "SETTINGS_GAMEPAD" },
  22: { cle: "GAMEPAD_BINDING", fr: "GAMEPAD_BINDING" },
  23: { cle: "SETTINGS_KEYBOARD", fr: "SETTINGS_KEYBOARD" },
  24: { cle: "KEYBOARD_BINDING", fr: "KEYBOARD_BINDING" },
  25: { cle: "ACHIEVEMENTS", fr: "ACHIEVEMENTS" },
  26: { cle: "GAME_STATS", fr: "GAME_STATS" },
  27: { cle: "EGG_LIST", fr: "EGG_LIST" },
  28: { cle: "EGG_GACHA", fr: "EGG_GACHA" },
  29: { cle: "POKEDEX", fr: "POKEDEX" },
  30: { cle: "POKEDEX_SCAN", fr: "POKEDEX_SCAN" },
  31: { cle: "POKEDEX_PAGE", fr: "POKEDEX_PAGE" },
  32: { cle: "LOGIN_OR_REGISTER", fr: "LOGIN_OR_REGISTER" },
  33: { cle: "LOGIN_FORM", fr: "LOGIN_FORM" },
  34: { cle: "REGISTRATION_FORM", fr: "REGISTRATION_FORM" },
  35: { cle: "LOADING", fr: "LOADING" },
  36: { cle: "UNAVAILABLE", fr: "UNAVAILABLE" },
  37: { cle: "CHALLENGE_SELECT", fr: "CHALLENGE_SELECT" },
  38: { cle: "RENAME_POKEMON", fr: "RENAME_POKEMON" },
  39: { cle: "RENAME_RUN", fr: "RENAME_RUN" },
  40: { cle: "RUN_HISTORY", fr: "RUN_HISTORY" },
  41: { cle: "RUN_INFO", fr: "RUN_INFO" },
  42: { cle: "TEST_DIALOGUE", fr: "TEST_DIALOGUE" },
  43: { cle: "AUTO_COMPLETE", fr: "AUTO_COMPLETE" },
  44: { cle: "ADMIN", fr: "ADMIN" },
  45: { cle: "MYSTERY_ENCOUNTER", fr: "MYSTERY_ENCOUNTER" },
  46: { cle: "CHANGE_PASSWORD_FORM", fr: "CHANGE_PASSWORD_FORM" },
  47: { cle: "ALERT_MODAL", fr: "ALERT_MODAL" },
};

export const WeatherType: Readonly<Record<number, Nom>> = {
  0: { cle: "NONE", fr: "Aucune" },
  1: { cle: "SUNNY", fr: "Soleil" },
  2: { cle: "RAIN", fr: "Pluie" },
  3: { cle: "SANDSTORM", fr: "Tempête de sable" },
  4: { cle: "HAIL", fr: "Grêle" },
  5: { cle: "SNOW", fr: "Neige" },
  6: { cle: "FOG", fr: "Brouillard" },
  7: { cle: "HEAVY_RAIN", fr: "Pluie battante" },
  8: { cle: "HARSH_SUN", fr: "Soleil intense" },
  9: { cle: "STRONG_WINDS", fr: "Vent mystérieux" },
};
